runtime: python310

instance_class: F4

inbound_services:
- warmup

automatic_scaling:
  min_idle_instances: 1

handlers:
- url: /
  script: auto
  secure: always

- url: /static
  static_dir: static
  secure: always
